### ISSUE TITLE
Fix ExerciseList to use a List value not ForEach for the allExercises array

### ISSUE THREAD

**Issue by soaapp** [soaapp/swift-jym#15]
Inside ExercisesView the allExercises array is currently being shown with ForEach to list values of array but will disappear when List is used. 

Needs further investigation. FIXME is added to code.

**Comment by soaapp** [comment]
[Found this](https://stackoverflow.com/questions/72819561/can-iterate-through-an-array-with-foreach-but-not-with-list) and removed scroll view in code but list view still doesn't show array values.

**Comment by arota18** [comment]
I've to go to work in something like 30 mins, after that and if you want, i can try to investigate on this issue.

**Comment by soaapp** [comment]
Hey there my friend, if you're ok with looking into it that would be great! No rush at all.👍
